---
language: python
services:
  - docker
install:
  - pip install molecule docker ansible-lint flake8
script:
  - molecule --version
  - ansible --version
  - molecule lint
  - molecule syntax
  - molecule test
