---

- name: Disable ntpdate
  service:
    name: ntpdate
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable sntp
  service:
    name: sntp
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable ptp4l
  service:
    name: ptp4l
    state: stopped
    enabled: false
  when: timesync_mode != 2
  ignore_errors: true

- name: Disable phc2sys
  service:
    name: phc2sys
    state: stopped
    enabled: false
  when: timesync_mode != 2 or not timesync_mode2_hwts
  ignore_errors: true

- name: Disable timemaster
  service:
    name: timemaster
    state: stopped
    enabled: false
  when: timesync_mode != 3
  ignore_errors: true
