---

- name: Install ntp
  package:
    name: ntp
    state: present
  when:
    - timesync_mode != 2

- import_tasks: a.yml

- name: Get ntp version
  command: rpm -q --qf '%{version}' ntp
  args:
    warn: false
  register: timesync_ntp_version
  changed_when: false
  check_mode: false
  when:
    - timesync_mode != 2

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    backup: true
    mode: 0644
  notify: restart {{ 'ntpd' if timesync_mode == 1 else 'timemaster' }}
  when:
    - timesync_mode != 2

- name: Generate ntpd sysconfig file
  template:
    src: ntpd.sysconfig.j2
    dest: /etc/sysconfig/ntpd
    backup: true
    mode: 0644
  notify: restart ntpd
  when:
    - timesync_mode == 1

- import_tasks: b.yml

- name: Disable chronyd
  service:
    name: chronyd
    state: stopped
    enabled: false
  ignore_errors: true

- import_tasks: c.yml

- name: Enable ntpd
  service:
    name: ntpd
    state: started
    enabled: true
  when:
    - timesync_mode == 1
